// This file was auto-generated by ML.NET Model Builder. 
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace MLModel1_ConsoleApp1
{
    public partial class MLModel1
    {
        /// <summary>
        /// model input class for MLModel1.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [ColumnName(@"Index")]
            public float Index { get; set; }

            [ColumnName(@"User Id")]
            public string User_Id { get; set; }

            [ColumnName(@"First Name")]
            public string First_Name { get; set; }

            [ColumnName(@"Last Name")]
            public string Last_Name { get; set; }

            [ColumnName(@"Sex")]
            public string Sex { get; set; }

            [ColumnName(@"Email")]
            public string Email { get; set; }

            [ColumnName(@"Phone")]
            public string Phone { get; set; }

            [ColumnName(@"Date of birth")]
            public string Date_of_birth { get; set; }

            [ColumnName(@"Job Title")]
            public string Job_Title { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for MLModel1.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"Index")]
            public float Index { get; set; }

            [ColumnName(@"User Id")]
            public float[] User_Id { get; set; }

            [ColumnName(@"First Name")]
            public float[] First_Name { get; set; }

            [ColumnName(@"Last Name")]
            public float[] Last_Name { get; set; }

            [ColumnName(@"Sex")]
            public uint Sex { get; set; }

            [ColumnName(@"Email")]
            public float[] Email { get; set; }

            [ColumnName(@"Phone")]
            public float[] Phone { get; set; }

            [ColumnName(@"Date of birth")]
            public float[] Date_of_birth { get; set; }

            [ColumnName(@"Job Title")]
            public float[] Job_Title { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"PredictedLabel")]
            public string PredictedLabel { get; set; }

            [ColumnName(@"Score")]
            public float[] Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("MLModel1.zip");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }

        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }
    }
}
