
// This file was auto-generated by ML.NET Model Builder. 

using MLModel1_ConsoleApp1;

// Create single instance of sample data from first line of dataset for model input
MLModel1.ModelInput sampleData = new MLModel1.ModelInput()
{
    Index = 2F,
    User_Id = @"f90cD3E76f1A9b9",
    First_Name = @"Phillip",
    Last_Name = @"Summers",
    Email = @"bethany14@example.com",
    Phone = @"214.112.6044x4913",
    Date_of_birth = @"1910-03-24",
    Job_Title = @"Phytotherapist",
};

// Make a single prediction on the sample data and print results
var predictionResult = MLModel1.Predict(sampleData);

Console.WriteLine("Using model to make single prediction -- Comparing actual Sex with predicted Sex from sample data...\n\n");


Console.WriteLine($"Index: {2F}");
Console.WriteLine($"User_Id: {@"f90cD3E76f1A9b9"}");
Console.WriteLine($"First_Name: {@"Phillip"}");
Console.WriteLine($"Last_Name: {@"Summers"}");
Console.WriteLine($"Sex: {@"Female"}");
Console.WriteLine($"Email: {@"bethany14@example.com"}");
Console.WriteLine($"Phone: {@"214.112.6044x4913"}");
Console.WriteLine($"Date_of_birth: {@"1910-03-24"}");
Console.WriteLine($"Job_Title: {@"Phytotherapist"}");


Console.WriteLine($"\n\nPredicted Sex: {predictionResult.PredictedLabel}\n\n");
Console.WriteLine("=============== End of process, hit any key to finish ===============");
Console.ReadKey();

